---
- name: Install Jenkins on Amazon Linux 2
  hosts: n2
  become: yes

  tasks:
    - name: Install Amazon Corretto 11
      ansible.builtin.yum:
        name: java-11-amazon-corretto
        state: present

    - name: Download Jenkins RPM package
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins-2.462.1-1.1.noarch.rpm
        dest: /tmp/jenkins.rpm

    - name: Install Jenkins package with GPG check disabled
      ansible.builtin.yum:
        name: /tmp/jenkins.rpm
        state: present
        disable_gpg_check: yes

    - name: Enable Jenkins service to start on boot
      ansible.builtin.systemd:
        name: jenkins
        enabled: yes

    - name: Start Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: started

    - name: Show Jenkins version
      ansible.builtin.command:
        cmd: jenkins --version
      register: jenkins_version_output

    - name: Display Jenkins version
      ansible.builtin.debug:
        msg: "Jenkins version: {{ jenkins_version_output.stdout }}"

    - name: Show Java version
      ansible.builtin.command:
        cmd: java -version
      register: java_version_output
      ignore_errors: yes

    - name: Display Java version
      ansible.builtin.debug:
        msg: "Java version: {{ java_version_output.stderr }}"
