---
- name: Install Jenkins on Amazon Linux 2
  hosts: n2
  become: yes

  tasks:
    - name: Install Amazon Corretto 11
      ansible.builtin.yum:
        name: java-11-amazon-corretto
        state: present

    - name: Add Jenkins repository GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat/jenkins.io.key

    - name: Add Jenkins repository
      ansible.builtin.yum_repository:
        name: jenkins
        description: Jenkins Stable Repo
        baseurl: https://pkg.jenkins.io/redhat-stable/
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
        enabled: yes

    - name: Install Jenkins
      ansible.builtin.yum:
        name: jenkins
        state: present

    - name: Start Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: yes

    - name: Open Jenkins port in the firewall
      ansible.builtin.firewalld:
        service: jenkins
        permanent: yes
        state: enabled
        immediate: yes
