---
- name: Install Jenkins on Amazon Linux 2
  hosts: n1
  become: yes

  tasks:
    - name: Install Java OpenJDK 11
      amazon.aws.yum:
        name: java-11-openjdk
        state: present

    - name: Add Jenkins repository
      amazon.aws.yum_repository:
        name: jenkins
        description: Jenkins Stable Repo
        baseurl: https://pkg.jenkins.io/redhat-stable/
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
        enabled: yes

    - name: Install Jenkins
      amazon.aws.yum:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Open Jenkins port in the firewall
      amazon.aws.firewalld:
        service: jenkins
        permanent: yes
        state: enabled
        immediate: yes
