---
- name: Install Jenkins on Amazon Linux 2
  hosts: n2
  become: yes

  tasks:
    - name: Install Amazon Corretto 11
      ansible.builtin.yum:
        name: java-11-amazon-corretto
        state: present

    - name: Download Jenkins RPM package
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins-2.462.1-1.1.noarch.rpm
        dest: /tmp/jenkins.rpm

    - name: Install Jenkins package with GPG check disabled
      ansible.builtin.yum:
        name: /tmp/jenkins.rpm
        state: present
        disable_gpg_check: yes

    - name: Start Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: yes

    - name: Open Jenkins port in the firewall
      ansible.builtin.firewalld:
        service: jenkins
        permanent: yes
        state: enabled
        immediate: yes
