---
- hosts: n1
  become: yes
  vars:
    flask_app_directory: /opt/flask_app
    flask_app_service: flask_app
    repository_url: https://github.com/Etimdevops/flaskproject.git
    python_version: python3.11
    python_source_url: https://www.python.org/ftp/python/3.11.5/Python-3.11.5.tgz

  tasks:
    - name: Ensure necessary packages are installed
      ansible.builtin.yum:
        name:
          - git
          - "{{ python_version }}"
          - "{{ python_version }}-pip"
        state: present

    - name: Install python3-venv if not present
      ansible.builtin.yum:
        name: python3-venv
        state: present
        enablerepo: epel

    - name: Download Python source
      ansible.builtin.get_url:
        url: "{{ python_source_url }}"
        dest: /tmp/Python-3.11.5.tgz

    - name: Extract Python source
      ansible.builtin.unarchive:
        src: /tmp/Python-3.11.5.tgz
        dest: /tmp/
        remote_src: yes

    - name: Build and install python3-venv from source
      ansible.builtin.command:
        cmd: "cd /tmp/Python-3.11.5 && ./configure && make && make install"
        creates: /usr/local/bin/python3.11

    - name: Clone Flask application repository
      ansible.builtin.git:
        repo: "{{ repository_url }}"
        dest: "{{ flask_app_directory }}"
        version: main
        force: yes

    - name: Create virtual environment
      ansible.builtin.command:
        cmd: "{{ python_version }} -m venv {{ flask_app_directory }}/venv"
        creates: "{{ flask_app_directory }}/venv"

    - name: Install Flask application dependencies
      ansible.builtin.pip:
        requirements: "{{ flask_app_directory }}/requirements.txt"
        virtualenv: "{{ flask_app_directory }}/venv"

    - name: Copy Flask application service file to target machine
      ansible.builtin.template:
        src: flask_app.service.j2
        dest: /etc/systemd/system/flask_app.service
      notify:
        - Reload systemd
        - Start Flask application

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start Flask application
      ansible.builtin.systemd:
        name: flask_app
        state: started
        enabled: yes
