---
- name: Install Flask Application Dependencies
  hosts: all
  become: yes
  vars:
    venv_path: /opt/myapp/venv
    requirements_file: /opt/myapp/requirements.txt
    app_directory: /opt/myapp

  tasks:
    - name: Ensure Python 3 and pip are installed
      package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Create application directory
      file:
        path: "{{ app_directory }}"
        state: directory

    - name: Create virtual environment (optional)
      command: python3 -m venv "{{ venv_path }}"
      args:
        creates: "{{ venv_path }}/bin/activate"
      when: virtualenv | bool

    - name: Install Flask and required dependencies
      pip:
        name:
          - Flask
          - Werkzeug
          - Jinja2
          - Click
          - itsdangerous
          - MarkupSafe
        state: present
        executable: "{{ venv_path }}/bin/pip"  # Use virtualenv pip if created

    - name: Install optional Flask extensions
      pip:
        name:
          - Flask-SQLAlchemy
          - Flask-Migrate
          - Flask-WTF
          - Flask-Login
          - Flask-Mail
        state: present
        executable: "{{ venv_path }}/bin/pip"  # Use virtualenv pip if created

    - name: Install Gunicorn for production (optional)
      pip:
        name: gunicorn
        state: present
        executable: "{{ venv_path }}/bin/pip"  # Use virtualenv pip if created

    - name: Copy requirements.txt to application directory (optional)
      copy:
        src: /path/to/your/local/requirements.txt
        dest: "{{ requirements_file }}"
      when: requirements_file is defined

    - name: Install dependencies from requirements.txt (optional)
      pip:
        requirements: "{{ requirements_file }}"
        state: present
        executable: "{{ venv_path }}/bin/pip"  # Use virtualenv pip if created
      when: virtualenv | bool and requirements_file is defined
      args:
        chdir: "{{ app_directory }}"
