- name: Deploy Flask Application
  hosts: n1
  become: yes
  vars:
    flask_app_directory: /home/ec2-user/flaskproject  # Adjust as necessary
    git_repo_url: https://github.com/Etimdevops/flaskproject.git  # Replace with your GitHub repo URL
    git_clone_dir: /home/ec2-user/flaskproject

  tasks:
    - name: Ensure Flask app directory exists
      file:
        path: "{{ flask_app_directory }}"
        state: directory
        owner: ec2-user
        group: ec2-user

    - name: Clone Flask application repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_clone_dir }}"
        clone: yes
        update: yes
        version: master  # Adjust branch or tag if necessary

    - name: Copy Flask service file
      template:
        src: flask_app.service.j2
        dest: /etc/systemd/system/flask_app.service

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Start and enable Flask service
      systemd:
        name: flask_app
        state: started
        enabled: yes
