- name: Deploy Flask Application
  hosts: n1
  become: yes
  vars:
    flask_app_directory: /home/ec2-user/flaskproject
  tasks:
    - name: Ensure Flask app directory exists
      file:
        path: "{{ flask_app_directory }}"
        state: directory
        owner: ec2-user
        group: ec2-user

    - name: Copy Flask application files
      copy:
        src: /home/ec2-user/flaskproject
        dest: "{{ flask_app_directory }}"
        owner: ec2-user
        group: ec2-user
        mode: '0755'
        recurse: yes

    - name: Copy Flask service file
      template:
        src: flask_app.service.j2
        dest: /etc/systemd/system/flask_app.service

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Start and enable Flask service
      systemd:
        name: flask_app
        state: started
        enabled: yes
