---
- name: Setup Flask Application as Systemd Service
  hosts: all
  become: yes
  vars:
    flask_app_path: /home/ec2-user/flaskproject
    flask_app_file: app.py
    venv_path: /home/ec2-user/flaskproject/venv/bin/python

  tasks:
    - name: Ensure Flask application directory exists
      file:
        path: "{{ flask_app_path }}"
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Ensure Flask application file exists
      file:
        path: "{{ flask_app_path }}/{{ flask_app_file }}"
        state: file
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Create systemd service file for Flask application
      copy:
        dest: /etc/systemd/system/flask_app.service
        content: |
          [Unit]
          Description=Flask Application
          After=network.target

          [Service]
          ExecStart={{ venv_path }} {{ flask_app_path }}/{{ flask_app_file }}
          WorkingDirectory={{ flask_app_path }}
          Restart=always
          User=ec2-user
          Group=ec2-user

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start Flask application service
      systemd:
        name: flask_app
        state: started
        enabled: yes
